env:
  params:
    state_format: discrete

model:
  hidden_sizes: [256, 256, 256]
  hidden_activations: [ReLU, ReLU, ReLU]
  output_activation: null

train:
  base_dir: "runs"
  num_episodes: 5000
  gamma: 0.99
  epsilon_max: 1.0
  epsilon_min: 0.01
  epsilon_decay: 0.9999
  learning_rate: 0.0001
  memory_size: 100000
  batch_size: 32
  target_network: True
  target_update_freq: 20