env:
  id: TetrisA-v0
  params:
    state_format: features
    action_type: simple
    max_steps: 15000

model:
  hidden_sizes: [512, 512]
  hidden_activations: [ReLU, ReLU]
  output_activation: null

train:
  base_dir: "runs"
  num_episodes: 10000
  gamma: 0.99
  epsilon_max: 1.0
  epsilon_min: 0.01
  epsilon_decay: 0.9999
  learning_rate: 0.00001
  memory_size: 100000
  batch_size: 32
  target_network: True
  target_update_freq: 20
